export let langJp = {
    'user_status'      : '配信状態' ,
    'campaign_name'    : 'キャンペーン名' ,
    'ad_style'         : '広告タイプ' ,
    'ad_group_name'    : '広告グループ名' ,
    'ad_id'            : '入稿番号', 
    'cpa'              : 'CPA', 
    'conv_cnt'         : '獲得数',
    'client_cv'        : 'クライアントCV数',
    'total_click_cost' : '消化金額',
    'imps'             : 'IMP',
    'click_cnt'        : 'クリック数',
    'click_rate'       : 'CTR',
    'avg_click_cost'   : 'CPC',
    'avg_deliver_rank' : '平均掲載順位',
    'ad_headline'      : 'タイトル',
    'ad_description'   : '説明文',
    'ad_description2'  : '説明文２',
    'user_status_0'    : 'オフ',
    'user_status_1'    : 'オン',
    'ad_style_0'       : 'テキスト',
    'ad_style_1'       : '画像',
    'ad_style_2'       : '動画',
}

